{{--
    Landing page for the generated examples. Rendered by tests/ExamplesTest.php
    with the same $groups manifest used to build the individual pages, so the
    links here always stay in sync with what was generated.
--}}
<x-ex::layout title="Examples" theme="slate">
    <div class="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        <header class="mb-10 flex items-start justify-between gap-4">
            <div>
                <div class="mb-3 flex items-center gap-2">
                    <span class="flex h-9 w-9 items-center justify-center rounded-lg bg-sky-500 text-white">
                        <i class="ph ph-cube text-lg" aria-hidden="true"></i>
                    </span>
                    <span class="font-semibold tracking-tight">laravel-twcss-components</span>
                </div>
                <h1 class="text-3xl font-bold tracking-tight">Full-page examples</h1>
                <p class="mt-2 max-w-2xl text-sm opacity-70">
                    Static pages composed entirely from <code class="rounded bg-slate-200 px-1 py-0.5 text-xs dark:bg-slate-800">&lt;x-fltc::…&gt;</code>
                    components. Generated by the test suite. Toggle dark mode in the corner of any page.
                </p>
            </div>
            <x-fltc::darkmode.toggle />
        </header>

        <div class="space-y-10">
            @foreach ($groups as $group)
                <section>
                    <h2 class="mb-4 text-sm font-semibold uppercase tracking-wider opacity-60">{{ $group['title'] }}</h2>
                    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                        @foreach ($group['items'] as $item)
                            <a href="{{ $item['slug'] }}.html"
                               class="group flex flex-col rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-700 dark:bg-slate-900">
                                <span class="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100 text-slate-600 transition group-hover:bg-sky-500 group-hover:text-white dark:bg-slate-800 dark:text-slate-300">
                                    <i class="{{ $item['icon'] }} text-lg" aria-hidden="true"></i>
                                </span>
                                <span class="font-semibold">{{ $item['label'] }}</span>
                                <span class="mt-1 text-sm opacity-60">{{ $item['desc'] }}</span>
                                <span class="mt-3 inline-flex items-center gap-1 text-sm font-medium text-sky-600 dark:text-sky-400">
                                    Open <i class="ph ph-arrow-right transition group-hover:translate-x-0.5" aria-hidden="true"></i>
                                </span>
                            </a>
                        @endforeach
                    </div>
                </section>
            @endforeach
        </div>

        <footer class="mt-12 border-t border-slate-200 pt-6 text-xs opacity-50 dark:border-slate-700">
            Regenerate with <code>./test.sh</code>. Styling via the Tailwind Play CDN — for prototyping only.
        </footer>
    </div>
</x-ex::layout>
